"use client";

import type { ProductRecommendation, Incentive } from "@/lib/types";

const CATEGORY_LABELS: Record<string, string> = {
  solar_ppa: "Solar PPA",
  hvac: "HVAC / Heat Pump",
  insulation: "Insulation",
  electrical: "Electrical Upgrade",
  roofing: "Roofing",
  battery_storage: "Battery Storage",
};

const CATEGORY_ICONS: Record<string, string> = {
  solar_ppa: "☀️",
  hvac: "🌡️",
  insulation: "🏠",
  electrical: "⚡",
  roofing: "🏗️",
  battery_storage: "🔋",
};

const PRIORITY_COLORS: Record<string, string> = {
  high: "bg-ecosave-100 text-ecosave-800 border-ecosave-200",
  medium: "bg-yellow-50 text-yellow-800 border-yellow-200",
  low: "bg-gray-100 text-gray-600 border-gray-200",
};

const SCOPE_BADGE: Record<string, string> = {
  federal: "bg-blue-100 text-blue-700",
  state: "bg-purple-100 text-purple-700",
  utility: "bg-green-100 text-green-700",
};

interface Props {
  proposal: string;
  products: ProductRecommendation[];
  incentives: Incentive[];
  customerName: string;
  onReset: () => void;
}

// Simple markdown → HTML (no external dependency)
function renderMarkdown(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/^(\d+)\. (.+)$/gm, "<li>$2</li>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[h|u|o|l])/gm, "")
    .replace(/^(.+)$/gm, (line) =>
      line.startsWith("<") ? line : `<p>${line}</p>`
    );
}

export function ProposalResult({ proposal, products, incentives, customerName, onReset }: Props) {
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-ecosave-800">
            Proposal for {customerName}
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Generated by EcoSave AI Pipeline · {new Date().toLocaleDateString()}
          </p>
        </div>
        <button
          onClick={onReset}
          className="text-sm text-ecosave-600 hover:text-ecosave-800 border border-ecosave-200 rounded-lg px-3 py-1.5"
        >
          New Proposal
        </button>
      </div>

      {/* Products */}
      <section>
        <h2 className="text-lg font-semibold text-gray-700 mb-3">Recommended Solutions</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {products.map((p, i) => (
            <div
              key={i}
              className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 space-y-2"
            >
              <div className="flex items-center justify-between">
                <span className="font-semibold text-gray-800 text-sm">
                  {CATEGORY_ICONS[p.category]} {CATEGORY_LABELS[p.category] ?? p.category}
                </span>
                <span
                  className={`text-xs font-medium px-2 py-0.5 rounded-full border ${PRIORITY_COLORS[p.priority]}`}
                >
                  {p.priority} priority
                </span>
              </div>
              <p className="text-sm font-medium text-ecosave-700">{p.productName}</p>
              <p className="text-xs text-gray-500 leading-relaxed">{p.rationale}</p>
              <div className="flex items-center gap-2 pt-1">
                <span className="text-xs text-gray-400">Timeline: {p.estimatedTimeline}</span>
              </div>
              {p.compatibleIncentives.length > 0 && (
                <div className="flex flex-wrap gap-1 pt-1">
                  {p.compatibleIncentives.slice(0, 2).map((inc, j) => (
                    <span
                      key={j}
                      className="text-xs bg-ecosave-50 text-ecosave-700 rounded px-1.5 py-0.5 truncate max-w-full"
                      title={inc}
                    >
                      {inc.length > 35 ? inc.slice(0, 35) + "…" : inc}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Proposal narrative */}
      <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
        <h2 className="text-lg font-semibold text-gray-700 mb-4">Full Proposal</h2>
        <div
          className="proposal-content text-sm text-gray-700"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(proposal) }}
        />
      </section>

      {/* Incentives */}
      <section>
        <h2 className="text-lg font-semibold text-gray-700 mb-3">Applicable Incentive Programs</h2>
        <div className="space-y-3">
          {incentives.map((inc, i) => (
            <div
              key={i}
              className="bg-white rounded-xl border border-gray-100 shadow-sm p-4 flex gap-4"
            >
              <div className="flex-shrink-0">
                <span
                  className={`text-xs font-semibold px-2 py-1 rounded-full ${SCOPE_BADGE[inc.scope]}`}
                >
                  {inc.scope}
                </span>
              </div>
              <div className="space-y-1 min-w-0">
                <div className="font-medium text-sm text-gray-800">{inc.name}</div>
                <div className="text-xs text-ecosave-700 font-medium">{inc.amount}</div>
                <div className="text-xs text-gray-500 leading-relaxed">
                  {inc.eligibilityNotes}
                </div>
                <a
                  href={inc.sourceUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-ecosave-600 hover:underline"
                >
                  Official source →
                </a>
              </div>
            </div>
          ))}
        </div>
        <p className="text-xs text-gray-400 mt-3 italic">
          Incentive amounts shown are program maximums from official sources. Actual eligibility and amounts
          depend on individual circumstances. Consult a licensed tax professional and the program administrator
          before making financial decisions.
        </p>
      </section>

      {/* Print */}
      <div className="flex justify-center">
        <button
          onClick={() => window.print()}
          className="text-sm border border-gray-200 rounded-lg px-4 py-2 text-gray-600 hover:bg-gray-50"
        >
          Print / Save as PDF
        </button>
      </div>
    </div>
  );
}
